[docker] Fix some dependency-related hiccups
- Avrora does not compile with newer JDKs:

    src/avrora/syntax/atmel/AtmelParser.java:13: error: reference to Module is ambiguous
        public AtmelParser(InputStream stream, Module m, String fname) {
                                               ^
      both class avrora.syntax.Module in avrora.syntax and class java.lang.Module in java.lang match
    src/cck/test/TestEngine.java:194: error: method stop in class Thread cannot be applied to given types;
                            thread.stop(new NonTermination(now - thread.test_began));
                                  ^
      required: no arguments
      found: TestEngine.NonTermination
      reason: actual and formal argument lists differ in length

- SEGGER wants us to fill a form before we can download their software

- simavr needs  to be built  with RELEASE=1, otherwise  the executable
  loads its library from the compilation folder

- gave a simpler name to MSP430-GCC's installation folder

- automatically dump debug information when download commands fail